app_task:
    resource: "@AppBundle/Controller/TaskController.php"
    type:     annotation

app_comments:
    resource: "@AppBundle/Controller/CommentsController.php"
    type:     annotation

app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

app_category:
    resource: "@AppBundle/Controller/CategoryController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
